<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<html>
<head>
<title></title>
</head>
<body>
	<!-- 工商银行（借记卡） -->
	<table id="icbc_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
           <td>100万元</td>
			<td>100万元</td>
			<td>U盾用户</td>
       </tr>
       <tr>
           <td>100万元</td>
			<td>500万元</td>
			<td>二代U盾用户</td>
       </tr>
       <tr>
           <td>500元</td>
			<td>1,000元</td>
			<td>电子银行口令卡 -- 非手机短信认证客户</td>
       </tr>
       <tr>
           <td>2,000元</td>
			<td>5,000元</td>
			<td>电子银行口令卡 -- 口令卡手机短信认证客户</td>
       </tr>
       </tbody>
   </table>
   <!-- 工商银行（信用卡） -->
	<table id="icbc_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
           <td>100万元</td>
			<td>不超过信用卡额度，最高100万元</td>
			<td>U盾用户</td>
       </tr>
       <tr>
           <td>100万元</td>
			<td>不超过信用卡额度，最高100万元</td>
			<td>二代U盾用户</td>
       </tr>
       <tr>
           <td>500元</td>
			<td>1000元</td>
			<td>电子银行口令卡 -- 非手机短信认证客户</td>
       </tr>
       <tr>
           <td>2,000元</td>
			<td>5,000元</td>
			<td>电子银行口令卡 -- 口令卡手机短信认证客户</td>
       </tr>
       </tbody>
   </table>
   <!-- 农业银行（借记卡） -->
	<table id="abc_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
           <td>1,000元</td>
			<td>3,000元</td>
			<td>动态口令卡用户</td>
       </tr>
       <tr>
           <td>无限额</td>
			<td>无限额</td>
			<td>移动证书用户</td>
       </tr>
       </tbody>
   </table>
   <!-- 农业银行（信用卡） -->
	<table id="abc_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
           <td>1,000元</td>
			<td>3,000元</td>
			<td>动态口令卡用户</td>
       </tr>
       <tr>
           <td>无限额</td>
			<td>无限额</td>
			<td>移动证书用户</td>
       </tr>
       </tbody>
   </table>
   <!-- 中国银行（借记卡） -->
	<table id="boc_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
           <td>10,000元</td>
			<td>50,000元</td>
			<td>网银用户</td>
       </tr>
       </tbody>
   </table>
   <!-- 中国银行（信用卡） -->
	<table id="boc_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
           <td>5,000元</td>
			<td>不超过信用卡额度，最高5,000元</td>
			<td>网银用户</td>
       </tr>
       </tbody>
   </table>
   <!-- 建设银行（借记卡） -->
	<table id="ccb_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
           <td>1,000元</td>
			<td>1,000元</td>
			<td>开通网上支付功能</td>
       </tr>
       <tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>动态口令卡用户</td>					
		</tr>	
		<tr>
			<td>5万元</td>
			<td>10万元</td>
			<td>一代网银盾</td>					
		</tr>
		<tr>
			<td>50万元</td>
			<td>50万元</td>
			<td>二代网银盾</td>					
		</tr>
       </tbody>
   </table>
   <!-- 建设银行（信用卡） -->
	<table id="ccb_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
           <td>500元</td>
			<td>500元</td>
			<td>开通网上支付功能</td>
       </tr>
       </tbody>
   </table>
   <!-- 交通银行（借记卡） -->
	<table id="comm_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
           <td>5,000元</td>
			<td>5,000元</td>
			<td>手机注册版用户</td>
       </tr>
       <tr>
			<td>5万元</td>
			<td>5万元</td>
			<td>证书认证版用户</td>					
		</tr>	
       </tbody>
   </table>
   <!-- 交通银行（信用卡） -->
	<table id="comm_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>不超过信用卡额度，最高1,000元</td>
			<td>不超过信用卡额度，最高1,000元</td>
			<td>手机注册版用户</td>
		</tr>	
		<tr>
			<td>不超过信用卡额度，最高1,000元</td>
			<td>不超过信用卡额度，最高1,000元（单月限制3万元）</td>
			<td>证书认证版用户</td>						
		</tr>	
       </tbody>
   </table>
   <!-- 招商银行（借记卡） -->
	<table id="cmb_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>客户自行设定，最高无限额</td>
			<td>客户自行设定，最高无限额</td>
			<td>专业版用户</td>
		</tr>	
		<tr>
			<td>5,000元</td>
			<td>10,000元</td>
			<td>一卡通支付</td>					
		</tr>
		<tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>一卡通直付</td>					
		</tr>	
       </tbody>
   </table>
   <!-- 招商银行（信用卡） -->
	<table id="cmb_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>2,000元</td>
			<td>无限额</td>
			<td>实物类付款</td>
		</tr>	
		<tr>
			<td>500元</td>
			<td>无限额</td>
			<td>虚拟类付款</td>					
		</tr>	
       </tbody>
   </table>
   <!-- 浦发银行（借记卡） -->
	<table id="spdb_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>客户自行设定</td>
			<td>客户自行设定</td>
			<td>数字证书版用户</td>
		</tr>	
		<tr>
			<td>5万元</td>
			<td>5万元</td>
			<td>动态密码版用户</td>					
		</tr>
       </tbody>
   </table>
   <!-- 民生银行（借记卡） -->
	<table id="cmbc_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>短信验证码支付</td>
		</tr>	
		<tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>浏览器证书支付</td>					
		</tr>
		<tr>
			<td>50万元</td>
			<td>50万元</td>
			<td>动态口令（OTP）支付</td>					
		</tr>	
		<tr>
			<td>50万元</td>
			<td>50万元</td>
			<td>U宝支付</td>
		</tr>
       </tbody>
   </table>
   <!-- 民生银行（信用卡） -->
	<table id="cmbc_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>短信验证码支付</td>
		</tr>	
		<tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>浏览器证书支付</td>					
		</tr>
		<tr>
			<td>50万元</td>
			<td>50万元</td>
			<td>动态口令（OTP）支付</td>					
		</tr>	
		<tr>
			<td>50万元</td>
			<td>50万元</td>
			<td>U宝支付</td>
		</tr>
       </tbody>
   </table>
   <!-- 兴业银行（借记卡） -->
	<table id="cib_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>100万元</td>
			<td>100万元</td>
			<td>柜面开通支付功能 -- 网盾或短信口令</td>
		</tr>	
		<tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>柜面开通支付功能 -- 令牌保护</td>					
		</tr>
		<tr>
			<td>100万元</td>
			<td>100万元</td>
			<td>网银开通支付功能 -- 网盾</td>					
		</tr>	
		<tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>网银开通支付功能 -- 令牌或短信或令牌+短信</td>
		</tr>
       </tbody>
   </table>
   <!-- 兴业银行（信用卡） -->
	<table id="cib_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>客户信用卡额度</td>
			<td>客户信用卡额度</td>
			<td>无</td>
		</tr>	
       </tbody>
   </table>
   <!-- 光大银行（借记卡） -->
	<table id="ceb_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>浏览器证书用户</td>
		</tr>	
		<tr>
			<td>20万元</td>
			<td>50万元</td>
			<td>阳光网盾证书用户</td>					
		</tr>	
       </tbody>
   </table>
   <!-- 光大银行（信用卡） -->
	<table id="ceb_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>300元</td>
			<td>300元</td>
			<td>无</td>
		</tr>
       </tbody>
   </table>
   <!-- 平安银行（借记卡） -->
	<table id="pingan_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>5万元</td>
			<td>5万元</td>
			<td>手机动态口令用户</td>
		</tr>	
		<tr>
			<td>无限额</td>
			<td>无限额</td>
			<td>KEY盾</td>					
		</tr>
       </tbody>
   </table>
   <!-- 平安银行（信用卡） -->
	<table id="pingan_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>3,000元</td>
			<td>限制支付10次，总额3,000元</td>
			<td>无</td>	
		</tr>
       </tbody>
   </table>
   <!-- 中信银行（借记卡） -->
	<table id="citic_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>1,000元</td>
			<td>5,000元</td>
			<td>文件正式用户</td>
		</tr>	
		<tr>
			<td>10,000元</td>
			<td>50,000元</td>
			<td>动态口令文件证书用户</td>					
		</tr>	
		<tr>
			<td>无限额</td>
			<td>无限额</td>
			<td>USBKEY移动证书用户</td>					
		</tr>
       </tbody>
   </table>
   <!-- 中信银行（信用卡） -->
	<table id="citic_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>客户信用卡额度</td>
			<td>客户信用卡额度</td>
			<td>无</td>	
		</tr>
       </tbody>
   </table>
   <!-- 华夏银行（借记卡） -->
	<table id="hxb_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>无</td>
		</tr>
       </tbody>
   </table>
   <!-- 华夏银行（信用卡） -->
	<table id="hxb_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>不超过信用卡额度，最高5,000元</td>
			<td>不超过信用卡额度，最高5,000元</td>
			<td>无</td>	
		</tr>
       </tbody>
   </table>
   <!-- 广发银行（借记卡） -->
	<table id="cgb_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>手机动态验证码</td>
		</tr>
		<tr>
			<td>5万元</td>
			<td>5万元</td>
			<td>KEY令</td>						
		</tr>
		<tr>
			<td>100万元</td>
			<td>100万元</td>
			<td>Key盾</td>
		</tr>
       </tbody>
   </table>
   <!-- 广发银行（信用卡） -->
	<table id="cgb_11" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>5,000元</td>
			<td>5,000元</td>
			<td>手机动态验证码</td>
		</tr>
		<tr>
			<td>5万元</td>
			<td>5万元</td>
			<td>KEY令</td>						
		</tr>
		<tr>
			<td>100万元</td>
			<td>100万元</td>
			<td>Key盾</td>
		</tr>
       </tbody>
   </table>
   <!-- 邮储银行（借记卡） -->
	<table id="psbc_10" name="bankLimit" class="isShow">
       <thead>
       <tr>
           <th>单笔限额（元）</th>
           <th>单日限额（元）</th>
           <th>需要满足的条件</th>
       </tr>
       </thead>
       <tbody>
       <tr>
			<td>5万元</td>
			<td>5万元</td>
			<td>个人网银短信客户</td>
		</tr>
		<tr>
			<td>2万元</td>
			<td>2万元</td>
			<td>手机银行普通客户</td>						
		</tr>
		<tr>
			<td>200万元</td>
			<td>200万元</td>
			<td>手机银行万能版客户</td>
		</tr>
		<tr>
			<td>500万元</td>
			<td>500万元</td>
			<td>办理USB-KEY并开通短信服务金卡客户</td>
		</tr>
       </tbody>
   </table>
</body>
</html>